### PR TITLE
Challenge Submission

### PR DESCRIPTION
**Pull request by guoxiliu**

### CODE REVIEW

**Comment by ninamiolane** [comment]
Hi @guoxiliu , thank you for this great submission! 🎉 

Could you import your datasets using an external url (not uploading them on this GitHub repository)? I am afraid that Travis CI is not starting because the committed files are too large. Let me know if you encounter any problem? Thanks! :)

**Comment by guoxiliu** [comment]
Thanks for the feedback! The dataset used in the notebook is less than 10 MB, but I guess it's probably due to too many committed files. Let me try to fix the issue.

**Review by ninamiolane — APPROVED** [review]
Perfect, thank you for your reactivity! 🎉 

I approve the PR, but will leave it open for now, to avoid slowing down the Travis tests for the open PRs.

Thank you for the great submission, and we will be in touch for the voting process next week!

**Comment by guoxiliu** [comment]
In the notebook, we use `Plotly` to plot the figures (used in `Giotto-TDA` too), but the figures will not show in any static render of the notebooks. Will that be a problem?

**Comment by ninamiolane** [comment]
No problem with this, but thank you for the notice!

**Comment by ninamiolane** [comment]
Merging now, thank you for this great submission! 🎉 Stay tuned, as we will be in touch for the voting process.

**Comment by ninamiolane** [comment]
Hi @guoxiliu , the voting process is now open! 🎖️ 🎖️ 🎖️ 

Your team can record its vote using this form: https://forms.gle/NS74g5uyzmP4wKmb9
- Note that your team can fill this form only once. If you do not follow this rule, the vote will be cancelled.
- The deadline to fill the form is Thursday May 6th, 11:59 am PST.
- More details on the voting guidelines are available at the form's link above.

We look forward to deciding with you on the best open-source contributions in computational geometry and topology of the year! 🎉

**Comment by ninamiolane** [comment]
Hi @guoxiliu  , we have extended the deadline to submit your vote through the Google form to Thursday May 6th, 10 pm PST. 

If you haven't already, you can submit your vote using the form above. Recall that you can fill out the form once per team. 

If your team has already voted, feel free to ignore this message!

**Pull request merged**
