### PR TITLE
Submission for the challenge

### PR DESCRIPTION
**Pull request by bilalze**
INTRINSIC DISEASE MAPS USING PERSISTENT COHOMOLOGY

### CODE REVIEW

**Review by ninamiolane — CHANGES_REQUESTED** [review]
Thank you for this great submission! 🎉 

Travis tests need to pass before we can merge. So far, it is failing with the following error:
```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-8e18379f8cc4> in <module>
      3 import time
      4 import circularcoordinates
----> 5 import dionysus as d
      6 
      7 df = pd.read_csv('malaria.csv')
ModuleNotFoundError: No module named 'dionysus'
```
See here:https://travis-ci.org/github/geomstats/challenge-iclr-2021/builds/769253191

Since `dionysus` is not in the `requirements.txt` of this challenge, could you download it through: `!pip install dionysus`?

Thanks!

**Comment by bilalze** [comment]
> Thank you for this great submission! 🎉
> 
> Travis tests need to pass before we can merge. So far, it is failing with the following error:
> 
> ```
> ModuleNotFoundError                       Traceback (most recent call last)
> <ipython-input-1-8e18379f8cc4> in <module>
>       3 import time
>       4 import circularcoordinates
> ----> 5 import dionysus as d
>       6 
>       7 df = pd.read_csv('malaria.csv')
> ModuleNotFoundError: No module named 'dionysus'
> ```
> 
> See here:https://travis-ci.org/github/geomstats/challenge-iclr-2021/builds/769253191
> 
> Since `dionysus` is not in the `requirements.txt` of this challenge, could you download it through: `!pip install dionysus`?
> 
> Thanks!

i tried doing that its not working

**Comment by bilalze** [comment]
doesn't seem to install. I just commented it out. It's not part of the main task, just a comparison on the side. If you find a workaround let me know.

> Thank you for this great submission! 🎉
> 
> Travis tests need to pass before we can merge. So far, it is failing with the following error:
> 
> ```
> ModuleNotFoundError                       Traceback (most recent call last)
> <ipython-input-1-8e18379f8cc4> in <module>
>       3 import time
>       4 import circularcoordinates
> ----> 5 import dionysus as d
>       6 
>       7 df = pd.read_csv('malaria.csv')
> ModuleNotFoundError: No module named 'dionysus'
> ```
> 
> See here:https://travis-ci.org/github/geomstats/challenge-iclr-2021/builds/769253191
> 
> Since `dionysus` is not in the `requirements.txt` of this challenge, could you download it through: `!pip install dionysus`?
> 
> Thanks!

doesn't seem to install. I just commented it out. It's not part of the main task, just a comparison on the side. If you find a workaround let me know.

**Review by bilalze — COMMENTED** [review]
Pip install Dionysus does not work in the compiler. I commented it out since it's not part of the main analysis. Just a comparison on the side. If you find a fix lmk.

**Comment by ninamiolane** [comment]
Oh, I see. An alternative would be to adapt the command lines in `.travis.yml` to have `dionysus` installed there:
https://github.com/geomstats/challenge-iclr-2021/blob/3ec9786b82f2ea9f5f2333707b2b4e51b2f7b98a/.travis.yml#L10
using build guidelines here:
https://pypi.org/project/dionysus/

I let you decide if you want to go it, otherwise the submission looks great like this too!

**Review by ninamiolane — APPROVED** [review]
Approved! I let the PR opened for now, to avoid slowing down the Travis tests for the open PRs.

If you end up trying to install `dionysus`, let me know. Otherwise, thank you for the great submission, and we will be in touch for the voting process next week!

**Comment by bilalze** [comment]
> Approved! I let the PR opened for now, to avoid slowing down the Travis tests for the open PRs.
> 
> If you end up trying to install `dionysus`, let me know. Otherwise, thank you for the great submission, and we will be in touch for the voting process next week!

This is fine. I don't know how to do that.

**Comment by ninamiolane** [comment]
Merging now, thank you for this great submission! 🎉 Stay tuned, as we will be in touch for the voting process.

**Comment by ninamiolane** [comment]
Hi @bilalze , the voting process is now open! 🎖️ 🎖️ 🎖️ 

Your team can record its vote using this form: https://forms.gle/NS74g5uyzmP4wKmb9
- Note that your team can fill this form only once. If you do not follow this rule, the vote will be cancelled.
- The deadline to fill the form is Thursday May 6th, 11:59 am PST.
- More details on the voting guidelines are available at the form's link above.

We look forward to deciding with you on the best open-source contributions in computational geometry and topology of the year! 🎉

**Comment by ninamiolane** [comment]
Hi @bilalze  , we have extended the deadline to submit your vote through the Google form to Thursday May 6th, 10 pm PST. 

If you haven't already, you can submit your vote using the form above. Recall that you can fill out the form once per team. 

If your team has already voted, feel free to ignore this message!

**Comment by ninamiolane** [comment]
Hi @bilalze  , if you haven't replied yet, please check the issue #39 about asking your permission to be listed as a co-author on the challenge's white paper. Thank you!

**Pull request merged**
