### PR TITLE
Added gcorso notebook submission

### PR DESCRIPTION
**Pull request by gcorso**

### CODE REVIEW

**Comment by ninamiolane** [comment]
Thank you for this great submission! 🎉 

We need to fix the Travis tests before we can merge. Travis fails with this error:
`ImportError: cannot import name 'mst' from 'hierarchical_clustering.relaxed.mst' (unknown location)`
See here: https://travis-ci.org/github/geomstats/challenge-iclr-2021/builds/769058763

It seems that it cannot find your GitHub repository: `gcorso/neural_seed`.

Try replacing:
`!git clone https://github.com/gcorso/neural_seed.git`
with something like:
`!pip install git+https://github.com/gcorso/neural_seed.git#egg=neural_seed`?

**Comment by gcorso** [comment]
Dear Nina, thank you for the suggestion, I have now fixed all the import issues (I think) but the notebook gets killed because of a period of 10min without output. However, from the error travis gives I cannot even detect the line/cell when this happens making the debugging process very hard. As can be seen executing [this notebook](https://colab.research.google.com/github/gcorso/neural_seed/blob/master/tutorial/Neural_SEED.ipynb) on Google Colab hardware the notebook runs smoothly so I'm not sure where the problem lies. Do you have any suggestion on how to debug this type of issues with travis?

**Comment by gcorso** [comment]
My current understanding is that after 10 minutes of execution (even if the notebook code prints output in its cell) the notebook is killed. Could you confirm this is the case? If so shouldn't this limit be increased given that the guidelines say that it needs to run in 3h? Thanks for the help!

**Comment by ninamiolane** [comment]
Yes, this comes from the limitations of the Travis default settings. No problem, we will update Travis or run the notebook manually!

**Review by ninamiolane — APPROVED** [review]
Merging now, thank you for this great submission! 🎉 Stay tuned, as we will be in touch for the voting process.

**Comment by ninamiolane** [comment]
Hi @gcorso , the voting process is now open! 🎖️ 🎖️ 🎖️ 

Your team can record its vote using this form: https://forms.gle/NS74g5uyzmP4wKmb9
- Note that your team can fill this form only once. If you do not follow this rule, the vote will be cancelled.
- The deadline to fill the form is Thursday May 6th, 11:59 am PST.
- More details on the voting guidelines are available at the form's link above.

We look forward to deciding with you on the best open-source contributions in computational geometry and topology of the year! 🎉

**Comment by ninamiolane** [comment]
Hi @gcorso , we have extended the deadline to submit your vote through the Google form to Thursday May 6th, 10 pm PST. 

If you haven't already, you can submit your vote using the form above. Recall that you can fill out the form once per team. 

If your team has already voted, feel free to ignore this message!

**Pull request merged**
