### PR TITLE
Submission

### PR DESCRIPTION
**Pull request by pikulsomesh**
Hi 
This is my submission commit.
Best
Somesh

### CODE REVIEW

**Comment by ninamiolane** [comment]
Thank you for this great submission! 🎉

The Travis test needs to pass before we can merge. I think the error comes from your conda installs.

Could you try installing your packages directly in Travis, by editing the .travis.ylm file at the root of this repository (see section "install"), and removing the corresponding lines from your notebook. Thanks!

**Comment by pikulsomesh** [comment]
Hi 
I have updated the .travis.yml file, and commented out the conda install in the notebook. 
Could you please resolve the conflicts, or let me know if something else needs to be done?

The current conflicts in the `.travis.yml` file are for the 3 libraries used for processing of chemical/biological information - RDKit, MDTraj and Biopython. Please add them at your convenience.

```
  - conda install -c conda-forge rdkit
  - pip install biopython
  - conda install -c conda-forge mdtraj
  ```

Best
Somesh

**Comment by pikulsomesh** [comment]
Hi Nina
I hope with the Travis tests done, the code runs through. I created a new environment locally, and ran it through.
One thing that I came across is that Travis has a timeout of 10 minutes. However, my code takes about an hour and half to execute. 
Let me know how to address this! Should I reduce the sample size for the notebook?
Best
Somesh

**Comment by ninamiolane** [comment]
No problem, this is a limitation of the default Travis configuration and it is on our end. 

Could you resolve the GitHub conflicts in .travis.yml though? Thanks!

**Comment by pikulsomesh** [comment]
Hi Nina
Thanks for confirming! I have resolved the conflicts in .travis.yml now.
Somesh

**Review by ninamiolane — APPROVED** [review]
Perfect, thank you for resolving the conflicts and thank you for this great submission! 🎉 Stay tuned, as we will be in touch for the voting process.

**Comment by ninamiolane** [comment]
Hi @pikulsomesh , the voting process is now open! 🎖️ 🎖️ 🎖️ 

Your team can record its vote using this form: https://forms.gle/NS74g5uyzmP4wKmb9
- Note that your team can fill this form only once. If you do not follow this rule, the vote will be cancelled.
- The deadline to fill the form is Thursday May 6th, 11:59 am PST.
- More details on the voting guidelines are available at the form's link above.

We look forward to deciding with you on the best open-source contributions in computational geometry and topology of the year! 🎉

**Comment by ninamiolane** [comment]
Hi @pikulsomesh  , we have extended the deadline to submit your vote through the Google form to Thursday May 6th, 10 pm PST. 

If you haven't already, you can submit your vote using the form above. Recall that you can fill out the form once per team. 

If your team has already voted, feel free to ignore this message!

**Pull request merged**
