### PR TITLE
Antonio-Leitao Submission

### PR DESCRIPTION
**Pull request by antonio-leitao**

### CODE REVIEW

**Comment by antonio-leitao** [comment]
I'm not sure if I understand what is causing the error in this pull request.

**Comment by antonio-leitao** [comment]
The logs are not very useful either

**Comment by ninamiolane** [comment]
I restarted the Travis test and will have a look!

**Comment by ninamiolane** [comment]
@Antonio-Leitao , I added your plotly, plotly-orca requirements directly in Travis, see:
https://github.com/geomstats/challenge-iclr-2021/blob/a023b734f9debabd94a54616750c75baed621797/.travis.yml#L20

Could you remove the line `!conda install --yes --prefix {sys.prefix} -c plotly plotly-orca` from your notebook and try again? Thanks!

**Comment by antonio-leitao** [comment]
That didn't seem to be the issue

**Review by ninamiolane — APPROVED** [review]
Indeed, this seems to be a problem on our end. Merging now anyway, thank you for this great submission! 🎉 Stay tuned, as we will be in touch for the voting process.

**Review by ninamiolane — APPROVED** [review]
Indeed, this seems to be a problem on our end. Merging now anyway, thank you for this great submission! 🎉 Stay tuned, as we will be in touch for the voting process.

**Comment by ninamiolane** [comment]
Hi @Antonio-Leitao , the voting process is now open! 🎖️ 🎖️ 🎖️ 

Your team can record its vote using this form: https://forms.gle/NS74g5uyzmP4wKmb9
- Note that your team can fill this form only once. If you do not follow this rule, the vote will be cancelled.
- The deadline to fill the form is Thursday May 6th, 11:59 am PST.
- More details on the voting guidelines are available at the form's link above.

We look forward to deciding with you on the best open-source contributions in computational geometry and topology of the year! 🎉

**Comment by antonio-leitao** [comment]
thank you very much

**Comment by ninamiolane** [comment]
Hi @Antonio-Leitao , we have extended the deadline to submit your vote through the Google form to Thursday May 6th, 10 pm PST. 

If you haven't already, you can submit your vote using the form above. Recall that you can fill out the form once per team. 

If your team has already voted, feel free to ignore this message!

**Pull request merged**
