### PR TITLE
initial commit of submission notebook

### PR DESCRIPTION
**Pull request by mbauw**
Submission for participation to ICLR Computational Geometry & Topology Challenge 2021. Notebook of type "Benchmarking/profiling on geometric and topological methods against other methods for a public dataset", as suggested in the guidelines. Authors' names are indicated at the beginning of the notebook.

### CODE REVIEW

**Comment by ninamiolane** [comment]
Thank you for this great submission! 🎉 

We need to fix the Travis error, before we can merge - see checks above. Travis is failing with the following error:
`ImportError: cannot import name 'DensityFiltration' from 'gtda.images' (/home/travis/virtualenv/python3.8.7/lib/python3.8/site-packages/gtda/images/__init__.py)`
See here: https://travis-ci.org/github/geomstats/challenge-iclr-2021/builds/769047370

If you need a different giotto-tda version than the one installed through the requirements, maybe you could install it through `!pip install` within the notebook itself?

**Comment by mbauw** [comment]
Thank you for your very quick and encouraging answer. A `!{sys.executable} -m pip install giotto-tda-nightly` seems to fix the issue, as you suggested.

**Comment by ninamiolane** [comment]
Perfect! Merging it now! Note that you can still edit your submission with new PRs until the deadline - if you wish to.

**Comment by ninamiolane** [comment]
Hi @Blupblupblup , the voting process is now open! 🎖️ 🎖️ 🎖️ 

Your team can record its vote using this form: https://forms.gle/NS74g5uyzmP4wKmb9
- Note that your team can fill this form only once. If you do not follow this rule, the vote will be cancelled.
- The deadline to fill the form is Thursday May 6th, 11:59 am PST.
- More details on the voting guidelines are available at the form's link above.

We look forward to deciding with you on the best open-source contributions in computational geometry and topology of the year! 🎉

**Comment by ninamiolane** [comment]
Hi @Blupblupblup , we have extended the deadline to submit your vote through the Google form to Thursday May 6th, 10 pm PST. 

If you haven't already, you can submit your vote using the form above. Recall that you can fill out the form once per team. 

If your team has already voted, feel free to ignore this message!

**Comment by ninamiolane** [comment]
Hi @Blupblupblup , if you haven't replied yet, please check the issue #39 about asking your permission to be listed as a co-author on the challenge's white paper. Thank you!

**Pull request merged**
