### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by mihaelanistor**
Topological noise invariant features using Giotto-TDA and Geomstats

Members: Matei Bejan, Bogdan Luchian, Andrei Manolache, Armand Nicolicioiu, Mihaela Nistor
Coordinator: Conf. Dr. Mihai Stupariu
Affiliation: University of Bucharest

### CODE REVIEW

**Comment by mihaelanistor** [comment]
Hi, @ninamiolane! We still have the same problem:
"No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself."

Do you have any advice for us?

**Comment by ninamiolane** [comment]
This comes from the limitations of the Travis default settings. No problem, we will run the notebook manually!

**Review by ninamiolane — APPROVED** [review]
Merging now, thank you for this great submission! 🎉 Stay tuned, as we will be in touch for the voting process.

**Comment by ninamiolane** [comment]
Hi @mihaelanistor , the voting process is now open! 🎖️ 🎖️ 🎖️ 

Your team can record its vote using this form: https://forms.gle/NS74g5uyzmP4wKmb9
- Note that your team can fill this form only once. If you do not follow this rule, the vote will be cancelled.
- The deadline to fill the form is Thursday May 6th, 11:59 am PST.
- More details on the voting guidelines are available at the form's link above.

We look forward to deciding with you on the best open-source contributions in computational geometry and topology of the year! 🎉

**Comment by ninamiolane** [comment]
Hi @mihaelanistor  , we have extended the deadline to submit your vote through the Google form to Thursday May 6th, 10 pm PST. 

If you haven't already, you can submit your vote using the form above. Recall that you can fill out the form once per team. 

If your team has already voted, feel free to ignore this message!

**Pull request merged**
